### PR TITLE
Add phpRedExpert project

### PR DESCRIPTION
**Pull request by eugef**

### CODE REVIEW

**Comment by soveran** [comment]
Is it a client or a tool?

**Comment by eugef** [comment]
phpRedExpert is a tool to manage Redis datastore

**Comment by eugef** [comment]
Why this PR couldn't be merged?

**Comment by badboy** [comment]
It's not a client. It's a tool. If it should still be added, re-submit it as a change to `tools.json`

**Comment by eugef** [comment]
Ok, thanks

**Pull request closed without merging**
