### PR TITLE
Copy Editing for streams-intro.md

### PR DESCRIPTION
**Pull request by mbarkhau**
Fixed some typos and rephrased some things to more natural English.

### CODE REVIEW

**Comment by mbarkhau** [comment]
I just noticed some other similar pull requests. From what I can see, this PR includes all changes from #949 and #935.

**Comment by paulsnar** [comment]
Oh, that's great, I'll close #949 then.

**Comment by andrewsensus** [comment]
@mbarkhau If you'd like to add another one, the first sentence in the section ```Querying by range: XRANGE and XREVRANGE``` can replace ```two IDs, *start* end *end*``` with ```two IDs, *start* and *end*```

**Comment by mbarkhau** [comment]
@andrewsensus Good catch. I had a bit of trouble seeing what you mean, just writing an inline diff would have been quicker for me to see what you mean.

```diff
- *start* end *end*
+ *start* and *end*
```

**Comment by andrewsensus** [comment]
@mbarkhau Thanks! I didn't realize diff was a supported language code.

**Comment by mbarkhau** [comment]
Hi @antirez, I'm guessing this is too much at once? If so feel free to close.

**Comment by itamarhaber** [comment]
Thanks - closing.

**Comment by mbarkhau** [comment]
Such a shame.

**Comment by itamarhaber** [comment]
Please feel free to reopen and rebase. I apologize for the delay.

**Pull request closed without merging**
