### PR TITLE
Update clients.json

### PR DESCRIPTION
**Pull request by Qti3e**
New PHP Client

### CODE REVIEW

**Comment by badboy** [comment]
Please fix the JSON

**Comment by Qti3e** [comment]
Fixed

**Comment by cheprasov** [comment]
I believe, that your client must have more tests for to be added on the official site as a client.
Because, now client has not any tests.

**Comment by badboy** [comment]
Yup, it's pretty bare bones and incomplete. I'd be happy to add it when it's fully working. :)

**Pull request closed without merging**
