### PR TITLE
Added hollodotme/readis to client list

### PR DESCRIPTION
**Pull request by hollodotme**

### CODE REVIEW

**Comment by badboy** [comment]
That's not a client library.

**Comment by hollodotme** [comment]
Sorry, I don't understand. Why is e.g. https://github.com/cinience/RedisStudio listet on http://redis.io/clients, this isn't a client library but a GUI (for Windows), like my project (for web). 
Did I add my project in the wrong place?

**Comment by badboy** [comment]
Yup, you can add it to `tools.json`, RedisStudio is already listed there

**Comment by hollodotme** [comment]
OK, thank you, will provide another PR.

**Pull request closed without merging**
