### PR TITLE
Add Airbnb

### PR DESCRIPTION
**Pull request by itamarhaber**

### CODE REVIEW

**Comment by soveran** [comment]
I'm almost certain they use Redis, but that blog post doesn't look official, what do you think we should do?

**Comment by itamarhaber** [comment]
Agreed - I tried looking for a more official-looking source but regrettably
could locate anything. I guess we'll need to shelf this until they publish
something more revealing on http://nerds.airbnb.com

On Wed, Mar 4, 2015 at 9:33 AM, Michel Martens <notifications@github.com>
wrote:

> I'm almost certain they use Redis, but that blog post doesn't look
> official, what do you think we should do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antirez/redis-doc/pull/497#issuecomment-77109204>.
>



-- 

*Itamar Haber* | Chief Developers Advocate
*Redis Watch Newsletter <http://redislabs.com/redis-watch-archive> *-
Curator and Janitor
*Redis  <http://www.redislabs.com/>**Labs <http://www.redislabs.com/>
*- Enterprise-Class
Redis for Developers

Mobile: +1 (415) 688 2443
Mobile (IL): +972 (54) 567 9692
Email: itamar@redislabs.com
Skype: itamar.haber

Blog <http://redislabs.com/blog/>  |  Twitter
<https://twitter.com/redislabsinc/>  |  LinkedIn
<https://www.linkedin.com/company/redis-labs-inc>

<https://www.redislabs.com/company/redis-labs-careers>

**Comment by djanowski** [comment]
I agree!

(I dislike the Who's using Redis page more and more)

**Comment by antirez** [comment]
@djanowski I agree, we can just kill it.

**Pull request closed without merging**
