### PR TITLE
Add async-redis to c++ clients

### PR DESCRIPTION
**Pull request by hamidr**
An async redis library for C++ based on libevpp/boost-asio
https://github.com/hamidr/async-redis

### CODE REVIEW

**Comment by badboy** [comment]
Right now we link the author to a Twitter profile, therefore it should be a valid Twitter handle. If you don't have one, don't worry, just remove the author for now.

**Comment by hamidr** [comment]
yay
Thanks. should i resolve the conflict myself?
https://twitter.com/hamidr_

**Comment by badboy** [comment]
That would be wonderful and save me some time

**Comment by hamidr** [comment]
oops i made booboo

**Comment by hamidr** [comment]
nope everything seems ok. thanks in advance.

**Pull request merged**
