### PR TITLE
Update clients.json

### PR DESCRIPTION
**Pull request by ienaga**
RedisPlugin for Phalcon.
The correspondence of MySQL sharding.

### CODE REVIEW

**Comment by badboy** [comment]
Looks more like this should go into `tools.json`. It's not a stand-alone client, is it?

**Comment by ienaga** [comment]
yes. sorry

**Comment by badboy** [comment]
Currently redis.io links the author's name to Twitter. Is the name `ienaga` your Twitter handle? If not or you don't want it to be linked, please remove the author name.

**Comment by ienaga** [comment]
no. my account is "ienagatoshiyuki"
commit now.

**Comment by ienaga** [comment]
Thank you!

**Pull request merged**
