### PR TITLE
Update php-redis-client

### PR DESCRIPTION
**Pull request by cheprasov**
I believe that the client was tested well, I use the client in personal projects, and everyone can use it in they own projects too.
The client has regular tests on latest versions of Redis, like 2.6.17, 2.8.24, 3.0.7, 3.2.4 (and older). Also, it has 644 tests for each version of PHP. And it passed well on the next versions of PHP: 5.5, 5.6, 7.0, 7.1, hhvm. ( https://travis-ci.org/cheprasov/php-redis-client )
And the client has good performance ( https://github.com/cheprasov/php-redis-client-vs-predis-test ).
Also, I am watching for Redis and trying to add new features to the client quickly and efficiently.
And I recommend to use this client.
Thanks.

### CODE REVIEW

**Comment by cheprasov** [comment]
Why not? :)

**Comment by cheprasov** [comment]
@badboy 
I would be very pleased if you approve the PR.
Besides, it will help to develop the client better in the community.

**Comment by badboy** [comment]
Hey @cheprasov. Sorry for the lack of response. We currently don't have clear rules on what we mark as  recommended. I pretty much dislike that flag and would like to remove it anyway.
As I am neither a PHP programmer nor have I seen your client in use, I personally can't vouch for it.

**Comment by cheprasov** [comment]
@badboy Thanks for answer :) Please, do not worry.
I completely understand you. And I think the same, It is very strange to give recommendations without experience. Also, I closed the PR because I saw news about Redis 4.0 R1, And I decided to make a lot changes in the client, for to do the client better :)

**Comment by badboy** [comment]
Cool! We appreciate all clients libs, so it's good to see you working on it. Keep up the good work.

**Pull request closed without merging**
