### PR TITLE
Clarified when WATCH doesn't abort EXEC

### PR DESCRIPTION
**Pull request by ProgerXP**
As per #734 WATCH accounts for modifications by its own connection

### CODE REVIEW

**Comment by badboy** [comment]
What about changing the sub-sentence into something similar to:

> WATCHed keys might be changed inside the transaction without aborting it.

**Comment by ProgerXP** [comment]
Like this?

```
[we are asking Redis to perform]
the transaction only if none of the `WATCH`ed keys were modified. 
(But they might be changed by the same client inside the transaction without aborting it.
[More on this](https://github.com/antirez/redis-doc/issues/734).) 
[Otherwise the transaction is not entered at all.]
```

I think it's critical to explicitly say they can be changed by the same client only, because if they are changed in a transaction made by another client the WATCH will fail anyway.

**Comment by badboy** [comment]
Yes, do we then really need that link? IMO that issue is too large to give users helpful information in one go.

**Comment by ProgerXP** [comment]
It's definitely helpful because the docs already have a similar link later:
```
Otherwise the transaction is not entered at all. (Note that if you WATCH a volatile key and Redis expires the key after you WATCHed it, EXEC will still work. More on this.)
```

"More on this" here links to http://code.google.com/p/redis/issues/detail?id=270 which was very useful for me to understand the exact case about volatile keys. I believe it's the same with keys changed outside the transaction. The docs don't list examples and tests which the issue does.

It doesn't take up much space, does it?

**Comment by badboy** [comment]
Hm, I see. Alright then.

**Comment by ProgerXP** [comment]
Corrected the text, please check.

**Comment by badboy** [comment]
:shipit:

**Comment by ProgerXP** [comment]
Thank you!

**Pull request merged**
