### PR TITLE
Update clients.json

### PR DESCRIPTION
**Pull request by SeYoungLee**
add PL/SQL client library oredis

### CODE REVIEW

**Comment by charsyam** [comment]
@SeYoungLee Could you remove recommand section? Thanks :)

**Comment by SeYoungLee** [comment]
I removed recommand section. Thnnks~

**Comment by charsyam** [comment]
@SeYoungLee Please keep the first brace position :) Thanks.

**Comment by SeYoungLee** [comment]
I  corrected the first brace position. I'm sorry for bothering you.

**Comment by charsyam** [comment]
@SeYoungLee Thanks, merged :)

**Pull request merged**
