### PR TITLE
update lqrm author

### PR DESCRIPTION
**Pull request by halaei**
I guess I had to add my github username as author field.
Related to https://github.com/antirez/redis-doc/pull/998
Thanks

### CODE REVIEW

**Comment by itamarhaber** [comment]
Hello @halaei - the author field is supposed to contain Twitter handles (not GitHub usernames). Is this yours https://twitter.com/halaei?

**Comment by halaei** [comment]
I am a little bit confused @itamarhaber. As I see in https://redis.io/modules all the links are to github. Are you sure it is twitter?

```html
<td class="authors">
    <a href="https://github.com/antirez">antirez</a>
</td>
```
My twitter is https://twitter.com/halaeiv

**Comment by halaei** [comment]
Apparently something is wrong. This is a link from redis.io to a non-existing github account:
```html
<td class="authors">
                  <a href="https://github.com/fcerbelle">fcerbelle</a>
</td>
```
But the twitter account exists https://twitter.com/fcerbelle

**Comment by itamarhaber** [comment]
Ok, apparently I spoke out of my *ss. The twitter handle is used in clients, the github for  modules :/

Thanks for noting the discrepancies - I'll remedy them shortly. Meanwhile, merging this.

**Pull request merged**
