### PR TITLE
add r3c, a Redis Cluster C++ Client

### PR DESCRIPTION
**Pull request by eyjian**
r3c is a Redis Cluster C++ Client, based on hiredis and support standalone, it's easy to make and use, not depends on C++11 or later.

### CODE REVIEW

**Comment by eyjian** [comment]
@melo @soveran @thetamind Do you know what's problem?

**Comment by eyjian** [comment]
$ make -s
commands/bitfield.md bitfield
commands/bitfield.md underflows
make: *** [spell] Error 1？？？

**Comment by badboy** [comment]
Don't worry about the failures.

Right now we link the author to a Twitter profile, therefore it should be a valid Twitter handle. 
Is `@JianYi` your twitter handle?
If you don't have one, don't worry, just remove the author for now.

**Comment by eyjian** [comment]
@badboy Thank you help me to solve the submit pull problem

**Comment by badboy** [comment]
So do you own that [twitter account](https://twitter.com/JianYi) now?

**Comment by badboy** [comment]
:+1:

**Pull request merged**
