### PR TITLE
"Escaped" KEYS + formatted KEYS

### PR DESCRIPTION
**Pull request by itamarhaber**
Per @badboy_'s recommendation

### CODE REVIEW

**Comment by badboy** [comment]
Should be \`!KEYS\`

**Comment by seppo0010** [comment]
It should probably be \`!KEYS\` both times? :P

**Comment by badboy** [comment]
It should. But I can squash + fix that.

**Comment by itamarhaber** [comment]
Feeling too stupid right now to come up with a snappy response - I can't even fix a doc without borking  the compilation.

**Comment by badboy** [comment]
Nope, "compilation" is fine. And no problem, it's now fixed, so all good.

**Pull request merged**
