### PR TITLE
Minor correction ;)

### PR DESCRIPTION
**Pull request by itamarhaber**

### CODE REVIEW

**Comment by badboy** [comment]
What's `GA`? I'm in favor of not using abbrevations in documentation, as you can't expect everyone to know them :)

**Comment by itamarhaber** [comment]
True - GA == generally available. Should I resubmit the PR?

**Comment by badboy** [comment]
Yip, just force-push it

**Comment by itamarhaber** [comment]
I hope I figured out how to that - Git always gets the better of me :tongue:

**Comment by badboy** [comment]
Perfect!

**Pull request merged**
