### PR TITLE
Adding VB.NET Redis Client

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
Should my client implement all the Redis APIs to be official?

**Comment by hishamco** [comment]
@badboy I don't know what is the status of this PR

**Comment by badboy** [comment]
It's in thanks to @seamusabshere's effort.

**Comment by hishamco** [comment]
I wanna push new commands in my repo, so is there a way that VB.NET client will be identified in redis.io

**Comment by badboy** [comment]
It will be listed there soon.

**Comment by hishamco** [comment]
Thanks @badboy :smile:

**Pull request closed without merging**
