### PR TITLE
Removed recommendation flag for clients

### PR DESCRIPTION
**Pull request by cheprasov**
Let's remove the recommendation flag from clients, because you currently don't have clear rules on what you mark as recommended.
In addition, the recommendation flag makes uncompetitive of other clients.
I think it would be great if people choose the client is not based on you tips, because you do not know all the programming languages for to give right client recommendation.
Thanks,
The PR history https://github.com/antirez/redis-doc/pull/768

### CODE REVIEW

**Comment by badboy** [comment]
I'm completely in favor of this change. At the same time we should probably remove that column in the HTML output as well.

cc @antirez @djanowski

**Comment by charsyam** [comment]
@cheprasov @badboy I also agree with you :)

**Comment by cheprasov** [comment]
Added PR https://github.com/antirez/redis-io/pull/115 for removing that column in the HTML

**Comment by cheprasov** [comment]
up

**Comment by antirez** [comment]
I don't like this idea *if not* immediately replaced (at the same time we remove the recommendation) by an automated system that gives an automated score based on latest commits activity and number of stars in the latest N months + number of star in total. There is to come up with a good enough formula, but it's important that immediately an user can follow what looks like the "to go" solution instead of wasting time exploring abandoned clients.

**Comment by antirez** [comment]
Basically... something like that:

1. The activity *smailing face* remains the same, but becomes a count of number of commits in latest 3 months. If over a given threshold the client is marked as active.
2. The star instead will be removed completely, we'll just write near the client name (and sort by) the number of stars on Github in the latest 6 months.

Moreover all the clients that are not released under an OSS license should be removed.

**Comment by l4u** [comment]
@antirez Should we reopen this or create a new issue for removing the stars?
Some of the stars can be misleading to new users who want to pick a recommended client.

**Pull request closed without merging**
