### PR TITLE
Updated description for client: cheprasov/php-redis-client

### PR DESCRIPTION
**Pull request by cheprasov**

### CODE REVIEW

**Comment by cheprasov** [comment]
Hi @badboy Could you please review and merge the PR? :)

**Comment by badboy** [comment]
No, I don't do Redis work anymore.

**Comment by cheprasov** [comment]
@badboy Oh, sorry :) Anyway, have a good day :)

**Comment by itamarhaber** [comment]
Hello @cheprasov - thanks for the update, merging.

**Pull request merged**
