### PR TITLE
Add mruby redis client to list

### PR DESCRIPTION
**Pull request by davydovanton**
/cc @matsumoto-r

### CODE REVIEW

**Comment by matsumoto-r** [comment]
Wow! I appreciate it.

**Comment by davydovanton** [comment]
@badboy this PR is normal for you? :blush:

**Comment by badboy** [comment]
Authors are currently linked to a Twitter account. `matsumoto-r` is not one. If you remove that (simply make it `[]`), it's ready to merge

**Comment by davydovanton** [comment]
@badboy done

**Comment by davydovanton** [comment]
@badboy thanks! :+1:

**Comment by matsumoto-r** [comment]
My twitter account is `@matsumotry`.

**Pull request merged**
