### PR TITLE
correct the arrow direction in client-side-caching

### PR DESCRIPTION
**Pull request by hwware**
1. In section Avoiding race conditions, The arrow direction for describing data flow is wrong and a little bit misleading, this corrects the arrow direction to show the data flow from server to client...
2. fix a typo

### CODE REVIEW

**Comment by hwware** [comment]
@itamarhaber Hi Itamar, can you take look this issue? thanks.

**Comment by itamarhaber** [comment]
Please excuse the delay @hwware - I need to give the entire doc a once over and then I'll attend to the arrows. "Soon(tm)" ;)

**Comment by hwware** [comment]
@itamarhaber no problem, thank you Itamar :)

**Comment by daidaotong** [comment]
@itamarhaber np, thank you very much!

**Comment by hwware** [comment]
@itamarhaber np, thank you very much Itamar!

**Pull request merged**
