### PR TITLE
Adds @badboy to the hiredis team

### PR DESCRIPTION
**Pull request by itamarhaber**

### CODE REVIEW

**Comment by charsyam** [comment]
@itamarhaber looks good, but why do you add '_' after of badboy?

**Comment by badboy** [comment]
@charsyam because that's my nick ;)

**Comment by charsyam** [comment]
@badboy Ah, I just think your nickname is badboy. It was a chance to merge it by me. :)

**Comment by badboy** [comment]
It's with an underscore on Twitter, IRC and elsewhere

**Comment by itamarhaber** [comment]
Underscore all over, except here :)

**Pull request merged**
