### PR TITLE
Grammatical and clarity changes to cluster-spec

### PR DESCRIPTION
**Pull request by brettmclean**
I've reviewed the cluster-spec document and made changes where I felt grammar and sentence structure could be improved without changing the meaning.

### CODE REVIEW

**Comment by badboy** [comment]
Thanks! These are quite some changes (and GitHub won't even display them), so it will take some time to check everything, but I'll put it on my list.

**Comment by brettmclean** [comment]
Hmm. You're right. I'm getting a "Sorry, we're unable to render a diff of this document" message. It was working yesterday evening (North America time), so perhaps GitHub is busier now and they're not willing to spend CPU time rendering large diffs.

It looks like diffs for the individual commits are being rendered properly, so reviewing my changes commit-by-commit may be your best option.

Thanks for taking my work under consideration. Please let me know if you need any changes.

**Comment by brettmclean** [comment]
Is there something I can do to make these changes more manageable to review? I recognize it's an abnormally large pull request.

**Comment by badboy** [comment]
Probably not, but now that you bumped them, I wrote it on my whiteboard, so I don't forget. I hope to get a bit of time this weekend to review.

**Comment by brettmclean** [comment]
Awesome! Thanks for letting me know.

**Comment by badboy** [comment]
I read all of the changes. I squashed them into a single commit and merged it into master: https://github.com/antirez/redis-doc/commit/8d5ac1d1ccfd1b43319474103db17c075640816f

Thanks, @brettmclean, this should make the Cluster spec even more readable. Thanks for all the work.

**Pull request closed without merging**
