### PR TITLE
Update lettuce client

### PR DESCRIPTION
**Pull request by mp911de**
* Add recommended flag (ok with you?)
* Add url
* Changed description

### CODE REVIEW

**Comment by badboy** [comment]
I don't know anything about the Java community? Is it as popular as Jedis already?

**Comment by HeartSaVioR** [comment]
If Redis doesn't have a condition / requirement with "recommended", I personally think Github star / watch represents its popularity objectively.
(Maybe counts of contributors could represent the popularity between developers.)

- Jedis : https://github.com/xetorthio/jedis
- Redisson : https://github.com/mrniko/redisson
- Lettuce : https://github.com/mp911de/lettuce (https://github.com/wg/lettuce)

**Comment by mp911de** [comment]
@badboy What do you mean by popular? Downloads, contributors, stars, questions on StackOverflow, forum activity? 

lettuce gains activity and adoption in various areas. Maybe ask @itamarhaber, he has a pretty clear view on the community. In general agree with @HeartSaVioR.

Btw. some clients are listed active without actually being so (jredis, redis-protocol) and some are active without flag (mod-redis).

**Comment by badboy** [comment]
If Itamar knows, I'm fine. :)

I know about the various problems regarding the client list. As promised, I'll make sure we get this discussed today in London.

**Pull request merged**
