### PR TITLE
Specify behavior of flushall async on new keys

### PR DESCRIPTION
**Pull request by milescrawford**
As suggested in https://github.com/antirez/redis-io/issues/163#issuecomment-447572197

### CODE REVIEW

**Comment by itamarhaber** [comment]
@milescrawford me neither 😄

**Comment by milescrawford** [comment]
ha, okay, pinging @antirez and @simonw then. Thanks all!

**Comment by milescrawford** [comment]
Could someone please hit merge?

**Comment by itamarhaber** [comment]
@milescrawford - the moment has arrived. Please keep on the good work!

**Pull request merged**
